include:
  - project: tvconss/gitlab-tools
    ref: main
    file: sync-to-github/.gitlab-ci.yml

variables:
  GITHUB_REPO: "openclaw"


deploy:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DEPLOY_FOLDER: "/opt/apps/openclaw"
  before_script:
    - apk add --no-cache rsync
  script:
    - echo "--- Preparing deployment directory ---"
    - mkdir -p $DEPLOY_FOLDER

    - echo "--- Syncing files from CI workspace to server ---"
    - rsync -av --delete --exclude '.git' ./ $DEPLOY_FOLDER/

    - cd $DEPLOY_FOLDER
    - echo "--- Switched to deployment directory ---"
    - pwd

    - echo "--- Create env file from gitlab env ---"
    - cp $ENV_FILE .env

    - pwd
    - ls

    - echo "-- Restart docker compose ---"
    - docker compose down
    - docker compose up -d --build
  only:
    - master
  tags:
    - docker

stages:
  - sync-to-github
  - deploy